### ISSUE TITLE
packer execution time has increased by two/four times after updating the version from 1.1.4 to any higher version

### ISSUE THREAD

**Issue by varunm17** [hashicorp/packer-plugin-ansible#180] opened 2024-01-11 13:15 UTC
#### Overview of the Issue

We are using the latest version of Ansibe packer plugin version : `1.1.1`.

We are customising many different OS as per our requirements. We were using the version `1.1.4` for `packer-plugin-amazon` and we plan to use the latest version of the plugin (`1.2.9`), however after updating the plugin version we have observed that the build time has almost doubled in case of linux AMI's and for windows the build time has increased by almost 4 times.

#### Reproduction Steps

* Execute ansible playbook with version `1.1.4` and any higher version and you will observe the build times.
* We tested with all available version and we are summarising our observation about execution time

| **Operating System \ amazon packer plugin version**	 | **_1.1.4_**	| 1.1.5 |	1.1.6 |	1.2.0 |	1.2.1	 | **1.2.2**	| 1.2.3	| 1.2.4	| 1.2.5	| 1.2.6	| 1.2.7	| 1.2.8 | **1.2.9** |
|:---: | 	:---:  | :---:         |     :---:      |          :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |  :---: |
|Amazon Linux 2|	**_14 minutes, 4 seconds_**	|35 minutes, 2 seconds	|34 minutes, 22 seconds	|35 minutes, 3 seconds	|36 minutes, 30 seconds	|33 minutes, 31 seconds|	36 minutes, 9 seconds	|34 minutes, 31 seconds|	34 minutes, 43 seconds	|34 minutes, 58 seconds	|37 minutes, 47 seconds	|35 minutes, 32 seconds|	35 minutes, 47 seconds|
|Ubuntu 20	|**_19 minutes, 16 seconds_**	|46 minutes, 12 seconds|	46 minutes, 58 seconds|	44 minutes, 25 seconds	|43 minutes, 43 seconds|	 43 minutes, 50 seconds	|44 minutes, 43 seconds	|44 minutes, 43 seconds	|44 minutes, 43 seconds	|50 minutes, 15 seconds	|46 minutes, 11 seconds	|43 minutes, 14 seconds	|43 minutes, 41 seconds|
|Ubuntu 22	|**_20 minutes, 44 seconds_**	|42 minutes, 44 seconds|	45 minutes, 5 seconds|	45 minutes, 39 seconds	|43 minutes, 1 seconds|	42 minutes, 43 seconds	|41 minutes, 40 seconds	|42 minutes, 52 seconds	|42 minutes, 34 seconds	|43 minutes, 14 seconds|	42 minutes, 26 seconds	|42 minutes, 56 seconds	|43 minutes, 26 seconds|
|Windows 2019	|**_22 minutes, 22 seconds_**	|1 hours, 22 minutes, 35 seconds	|1 hours, 22 minutes, 54 seconds	|1 hours, 24 minutes, 6 seconds|	1 hours, 42 minutes, 14 seconds|	1 hours, 25 minutes, 36 seconds	|1 hours, 18 minutes, 47 seconds	|1 hours, 22 minutes, 25 seconds	|1 hours, 21 minutes, 53 seconds	|1 hours, 40 minutes, 21 seconds	|1 hours, 19 minutes, 19 seconds|	1 hours, 23 minutes, 43 seconds	|1 hours, 26 minutes, 1 seconds|

### Plugin and Packer version

Packer version: `1.10.0 [go1.20.11 linux amd64]`
Ansibe packer plugin version : `1.1.1`

### Operating system and Environment details

Operating System:

- AmazonLinux2
- Ubuntu20
- Ubuntu22
- WindowsServer 2019

### Log Fragments and crash.log files

For sharing the logs we have executed only few ansible playbooks, hence the execution time is on the lower end  but still we can observe the execution time after upgrading the plugin has increased significantly

| Operating System \ amazon packer plugin version	 | 1.1.4 - log fragment gist URL| 1.1.4 - execution time	|  1.2.9 - log fragment | 1.2.9- execution time |
|:---: | :---:  | :---:| :---:  | :---:| 
|Amazon Linux 2| [amazon_linux_2_plugin_version_1.1.4.log](https://gist.github.com/varunm17/d54aaa5d8bfee1771799cafa0598fd0e) | 3 minutes, 17 seconds| [amazon_linux_2_plugin_version_1.2.9.log](https://gist.github.com/varunm17/12d829f19b963c6e74dd1658638cd4de) | 6 minutes, 55 seconds|
|Ubuntu 20| [ubuntu_20_plugin_version_1.1.4.log](https://gist.github.com/varunm17/a5789f67d7a62435668242309c2fa8a2) | 3 minutes, 6 seconds|[ubuntu_20_plugin_version_1.2.9.log](https://gist.github.com/varunm17/d90aa57dc953e1a0bd298423a1dc75e9) | 5 minutes, 51 seconds|
|Ubuntu 22| [ubuntu_22_plugin_version_1.1.4.log](https://gist.github.com/varunm17/f40a72862a69cd85b2e47eacdfc3b8ae) | 2 minutes, 26 seconds|[ubuntu_22_plugin_version_1.2.9.log](https://gist.github.com/varunm17/c40c63f7d7bb93deccd10d9ca1de090e) | 4 minutes, 38 seconds|
|Windows Server 2019| [windows_2019_plugin_version_1.1.4.log](https://gist.github.com/varunm17/0f79ff3e8f4f1b41b76288fb149766a6) | 3 minutes, 17 seconds and 3 minutes, 3 seconds |[windows_2019_plugin_version_1.2.9.log](https://gist.github.com/varunm17/bc5f980f8642fe4a78ee1774e0b993ba) | 9 minutes, 3 seconds and 14 minutes, 27 seconds |

**Comment by lbajolet-hashicorp** [comment] 2024-01-11 15:30
Duplicate of https://github.com/hashicorp/packer-plugin-amazon/issues/449

Since the version of the Ansible plugin doesn't seem to change between both, it's likelier to be linked to the AWS plugin, so we'll focus on this issue only.

**Closed by lbajolet-hashicorp** 2024-01-11 15:30 UTC
Labels: bug
